language: node_js
sudo: false
node_js:
- stable
cache:
  directories:
  - node_modules
env:
  global:
  - secure: DCC7uPFoB4lkWnrYjlsIJj1TbRT9AMWN/yJttKHrSGaAYa1BKsHzad9MWGxOZsVGjXvA6MVqai0P/DSbzTLOyJVXytioG6gi5okDTFSoPkgSB7lpnik+j4PY0CKMy9TlDcgO5wY1KsegYaZ/IWrw6M1nsEMECZ4xQtPP8HpaSgQ=
  - secure: JVg99fHL7ru4wHwHu38ksI3qUGh72au5Cdtj//7SWWekE+HE+ZiZxX/H0/UX5Sf7bSsVXuZqLEnP1JFl7BCoHpaWm+4JPFkFV6CTvMCn26/8yixqOXZOy4xUDv/Ul1FeBYqxopbbO2IetfCBBX7A7aETKyutoFu/pTsIe5J9BaA=
  matrix:
  - BROWSER=PhantomJS npm_config_coverage=true
  - BROWSER=SL_Chrome
  - BROWSER=SL_Firefox
  - BROWSER=SL_Safari_7
  - BROWSER=SL_Safari_8
  - BROWSER=SL_IE_8
  - BROWSER=SL_IE_9
  - BROWSER=SL_IE_10
  - BROWSER=SL_IE_11
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#annotator
    on_success: change
    on_failure: change
